### ISSUE TITLE
Upgrading from 1.0.5 to 1.1.0 results in "Invalid non-string/buffer chunk while parsing file"

### ISSUE THREAD

**Issue by ajmas** [leebyron/flow-remove-types#23]
The project [cvmtl/cvmtl-webui](https://github.com/cvmtl/cvmtl-webui) was working on MacOS X 10.2, with NodeJS 6.7.0, but now without any code change results in the following error:

```
{ TypeError: Invalid non-string/buffer chunk while parsing file: /Users/ajmas/Projects/cvmtl/cvmtl-webui/node_modules/mapbox-gl/js/mapbox-gl.js
    at validChunk (/Users/ajmas/Projects/cvmtl/cvmtl-webui/node_modules/readable-stream/lib/_stream_writable.js:249:10)
    at DestroyableTransform.Writable.write (/Users/ajmas/Projects/cvmtl/cvmtl-webui/node_modules/readable-stream/lib/_stream_writable.js:272:53)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (/Users/ajmas/Projects/cvmtl/cvmtl-webui/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/ajmas/Projects/cvmtl/cvmtl-webui/node_modules/through/index.js:45:5)
    at Stream.transform (/Users/ajmas/Projects/cvmtl/cvmtl-webui/node_modules/unflowify/index.js:29:12)
    at _end (/Users/ajmas/Projects/cvmtl/cvmtl-webui/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/ajmas/Projects/cvmtl/cvmtl-webui/node_modules/through/index.js:74:5)
  filename: '/Users/ajmas/Projects/cvmtl/cvmtl-webui/node_modules/mapbox-gl/js/mapbox-gl.js',
```

Doing some investigation shows that it is the change of flow-remove-types from 1.0.5 to 1.1.0 that seems to be causing the issue. For the moment I have downgraded to 1.0.5 in my local install to resolve the issue.

Note, this happens when I do:

```node_modules/.bin/gulp build```

Any ideas as to the cause?

**Comment by leebyron** [comment]
Thanks for the report.

It's hard to tell from the information you have here since none of the stack information is relevant to flow-remove-types and you're using gulp instead of using flow-remove-types directly.

This new version included a minor breaking change for JS API users if you're using the JS API directly.

You may need to replace:

```js
var output = flowRemoveTypes(input);
```

with 

```
var output = flowRemoveTypes(input).toString();
```

Please let me know if that helps solve your issue

**Comment by leebyron** [comment]
Also check out the older task #13 if you're manually calling `flowRemoveTypes` from your gulp configuration code.

Closing this, but please re-open it if you encounter an unrelated repro case.

**Comment by ajmas** [comment]
Doing an `npm ls`, I see this is actually being included by [mapbox-gl](https://www.npmjs.com/package/mapbox-gl).

```
├─┬ mapbox-gl@0.27.0
│ ├─┬ bubleify@0.5.1
│ │ └─┬ buble@0.12.5
│ │   ├── acorn@3.3.0
│ │   ├─┬ acorn-jsx@3.0.1
│ │   │ └── acorn@3.3.0
│ │   ├─┬ acorn-object-spread@1.0.0
│ │   │ └── acorn@3.3.0
│ │   ├─┬ magic-string@0.14.0
│ │   │ └── vlq@0.2.1
│ │   └── minimist@1.2.0
│ ├── csscolorparser@1.0.3
│ ├── earcut@2.1.1
│ ├── feature-filter@2.2.0
│ ├── flow-remove-types@1.0.5
│ ├─┬ geojson-rewind@0.1.0
```

**Comment by leebyron** [comment]
That definitely looks suspect! I suggest opening an issue on mapbox-gl, `flow-remove-types` should only appear in their `devDependencies`.
